services:
  repository.tags:
    class: AppBundle\Repository\TagsRepository
    factory: ["@doctrine.orm.entity_manager", "getRepository"]
    arguments:
      - AppBundle:Tag

  repository.user:
      class: AppBundle\Repository\UserRepository
      factory: ["@doctrine.orm.entity_manager", "getRepository"]
      arguments:
        - AppBundle:User
