services:
  app.voter.job:
    class: AppBundle\Voter\JobVoter
    tags:
      - { name: security.voter }

  app.voter.show_all_jobs:
    class: AppBundle\Voter\ShowAllJobsVoter
    arguments:
      - "@session"
    tags:
      - {name: security.voter }

  app.voter.dummy:
    class: AppBundle\Voter\DummyVoter
    tags:
      - { name: security.voter }
